name: PowerEssentials
main: me.plugner.poweressentials.PowerEssentials
version: "1.0.0-SNAPSHOT"
api: ["1.0.0"]
load: POSTWORLD
author: Plugner
description: Essentials Commands plugin to PowerNukkit
website: https://github.com/Plugner/PowerEssentials

commands:
  gm:
    description: Gamemode command.
    aliases:
      - gamemode
    permission: poweressentials.gamemode

permissions:
  poweressentials.gamemode:
    description: "Allows the user to run the /gm command"
    # Optional
    # If a player don't have an allow-deny definition for this key, this default value will be used
    # Valid options: 
    # - true: the permission is granted by default to everybody
    # - false: the permission is revoked by default to everybody, including admins and OP
    # - op: the permission is revoked by default to everybody, but is granted to OP players
    # - notop: the permission is granted by default to everybody, but is revoked to OP players
    # Default value is false
    default: op
    
# TODO Add all possible configuration here
