name: PowerEssentials
main: me.plugner.poweressentials.PowerEssentials
version: "1.0.0-SNAPSHOT"
api: ["1.0.0"]
load: POSTWORLD
author: Plugner
description: Essentials Commands plugin to PowerNukkit
website: https://github.com/Plugner/PowerEssentials

commands:
  day:
    description: Day command.
    permission: poweressentials.timechange
  night:
    description: Night command.
    permission: poweressentials.timechange
  info:
    description: Info command.
    permission: poweressentials.serverinfo
  ban:
    description: Ban command.
    permission: poweressentials.ban
  kick:
    description: Kick command.
    permission: poweressentials.kick
  unban:
    description: Unban command.
    permission: poweressentials.ban
    aliases:
      - pardon
  fly:
    description: Fly command.
    permission: poweressentials.fly
    aliases:
      - flyingmode
      - ibelieveicanfly
  heal:
    description: Heal command.
    permission: poweressentials.heal
    aliases:
      - regen
      - regenerate
  gm:
    description: Gamemode command.
    aliases:
      - gamemode
    permission: poweressentials.gamemode
  invsee:
    description: Invsee command.
    aliases:
      - inv
      - lookinv
      - lookattheinventory
      - inventory
      - showinv
      - invofaplayer
    permission: poweressentials.invsee
  bc:
    description: Broadcast command.
    aliases:
      - broadcast
      - say2all
      - saytoall
      - saytoeveryone
      - alert
      - announce
      - announcement
    permission: poweressentials.gamemode
  tp:
    description: Teleport command.
    aliases:
      - teleport
      - tele
      - teleportation
      - teleport2
      - teleportto
      - goto
    permission: poweressentials.tp

permissions:
  poweressentials.gamemode:
    description: "Allows the user to run the /gm command"
    default: op
  poweressentials.tp:
    description: "Allows the user to run the /tp command"
    default: op
  poweressentials.broadcast:
    description: "Allows the user to run the /broadcast command"
    default: op
  poweressentials.firework:
    description: "Fireworks!!"
    default: op
  poweressentials.timechange:
    description: "Allows the user to run a day change command"
    default: op
  poweressentials.serverinfo:
    description: "Allows the user to get the Server and PowerEssentials infomation."
    default: op
  poweressentials.invsee:
    description: "Allows the user to look other players inventory."
    default: op
  poweressentials.fly:
    description: "Allows the user to fly using /fly command."
    default: op
  poweressentials.heal:
    description: "Allows to heal a user using /heal command."
    default: op
  poweressentials.ban:
    description: "Allows to ban and unban."
    default: op
  poweressentials.kick:
    description: "Allows to kick."
    default: op