name: PowerEssentials
main: me.plugner.poweressentials.PowerEssentials
version: "1.0.0-SNAPSHOT"
api: ["1.0.0"]
load: POSTWORLD
author: Plugner
description: Essentials Commands plugin to PowerNukkit
website: https://github.com/Plugner/PowerEssentials

commands:
  gm:
    description: Gamemode command.
    aliases:
      - gamemode
    permission: poweressentials.gamemode
  tp:
    description: Teleport command.
    aliases:
      - teleport
      - tele
      - teleportation
      - teleport2
      - teleportto
      - goto
    permission: poweressentials.tp

permissions:
  poweressentials.gamemode:
    description: "Allows the user to run the /gm command"
    default: op
  poweressentials.tp:
    description: "Allows the user to run the /tp command"
    default: op