name: PowerEssentials
main: me.plugner.poweressentials.PowerEssentials
version: "1.0.0-SNAPSHOT"
api: ["1.0.0"]
load: POSTWORLD
author: Plugner
description: Essentials Commands plugin to PowerNukkit
website: https://github.com/Plugner/PowerEssentials

commands:
  day:
    description: Day command.
    permission: poweressentials.timechange
  night:
    description: Night command.
    permission: poweressentials.timechange
  info:
    description: Info command.
    permission: poweressentials.serverinfo
  gm:
    description: Gamemode command.
    aliases:
      - gamemode
    permission: poweressentials.gamemode
  bc:
    description: Broadcast command.
    aliases:
      - broadcast
      - say2all
      - saytoall
      - saytoeveryone
      - alert
      - announce
      - announcement
    permission: poweressentials.gamemode
  tp:
    description: Teleport command.
    aliases:
      - teleport
      - tele
      - teleportation
      - teleport2
      - teleportto
      - goto
    permission: poweressentials.tp

permissions:
  poweressentials.gamemode:
    description: "Allows the user to run the /gm command"
    default: op
  poweressentials.tp:
    description: "Allows the user to run the /tp command"
    default: op
  poweressentials.broadcast:
    description: "Allows the user to run the /broadcast command"
    default: op
  poweressentials.firework:
    description: "Fireworks!!"
    default: op
  poweressentials.timechange:
    description: "Allows the user to run a day change command"
    default: op
  poweressentials.serverinfo:
    description: "Allows the user to get the Server and PowerEssentials infomation."
    default: op
